In [1]:
"""
date : 2020/08/10
name : kang
content : Numpy (수치해석 패키지) 실습하기
"""

'\ndate : 2020/08/10\nname : kang\ncontent : Numpy (수치해석 패키지) 실습하기\n'

In [3]:
import numpy as np

In [5]:
#벡터 생성
v1 = np.array([1,2,3,4,5])
v1


array([1, 2, 3, 4, 5])

In [9]:
v2 = np.arange(5)
v2

array([0, 1, 2, 3, 4])

In [12]:
#0~1 사이 임의의 실수 100개
rand1 = np.random.rand(100)
rand1

array([0.96536567, 0.31360486, 0.35930477, 0.91739868, 0.86265457,
       0.96494964, 0.5821184 , 0.91578386, 0.82023911, 0.1813875 ,
       0.95731683, 0.71529654, 0.0974777 , 0.05897485, 0.24684217,
       0.10527167, 0.22809764, 0.50645357, 0.80670618, 0.14588486,
       0.15856938, 0.31984675, 0.51645572, 0.40863562, 0.06381584,
       0.929316  , 0.41187165, 0.04792038, 0.69216021, 0.63494995,
       0.4286961 , 0.47726607, 0.14483777, 0.6200416 , 0.33027596,
       0.22368608, 0.14112118, 0.64526781, 0.1173082 , 0.09415318,
       0.94446004, 0.44875245, 0.66158695, 0.07330748, 0.02645934,
       0.86923391, 0.76811054, 0.09619705, 0.27204996, 0.46182401,
       0.36998465, 0.43174426, 0.614563  , 0.92441806, 0.92729144,
       0.24421064, 0.87433552, 0.17514907, 0.79895324, 0.2026658 ,
       0.70572861, 0.78348948, 0.75422924, 0.75936945, 0.75512602,
       0.05884316, 0.86666899, 0.8000796 , 0.42823796, 0.60056132,
       0.79031274, 0.48307447, 0.73969268, 0.3411644 , 0.01742

In [15]:
#표준정규분포를 따르는 실수 100개
rand2 = np.random.randn(100)
rand2

array([-0.95293307,  0.26753028,  0.21255371, -0.65499836,  2.38341738,
        0.43446095, -1.18076843,  0.15502899, -0.83866984, -0.30686829,
       -0.01806701, -1.71073787, -0.33171691,  0.19380433,  0.59015743,
        0.80522933,  0.42625837, -1.26475415, -0.16214649,  0.33109301,
        0.20994436,  0.67150317,  0.07119678, -0.19039084, -0.85855607,
        2.2137128 , -1.96428099, -0.20696854,  0.53572593, -0.182612  ,
        0.99010156,  0.61287103, -2.81252361,  0.38397021,  0.66855054,
       -1.26677447,  0.3586537 , -1.00801864, -0.69849035, -1.71963251,
       -0.80659787, -0.86259894, -0.52447506,  0.04078933,  0.60501469,
       -0.12360559, -0.96866345,  0.08039816,  1.34263682,  0.59410015,
       -0.0883764 ,  1.19982171,  1.01967911,  0.26718484,  1.43492178,
        0.14539009, -1.34062138,  1.3799136 ,  0.30401987, -2.29232439,
       -1.90682128,  0.26165578, -0.16129843,  0.57796548, -0.88073902,
        0.40046124,  0.49439437, -1.23112044,  0.98564258, -0.64

In [16]:
#평균 0, 표준 편차 1인 정규분포를 따르는 임의의 실수 100개
rand3 = np.random.normal(0,1,100)
rand3

array([-0.39120383,  0.15485417,  0.33765141, -1.53102518, -1.00100334,
        0.33487417,  0.30201765, -0.62950545,  0.60453015, -0.71153656,
        0.41899106,  0.33349995, -1.18104336, -1.54756885,  1.50775742,
       -0.07111925,  0.12764821,  0.08167555, -1.65609679,  0.13491499,
        0.36332204,  1.5008728 , -0.71115581,  1.59014206,  0.22368339,
        0.88648041, -0.68496712,  1.51622394,  0.0256486 , -0.4399578 ,
       -0.63076099, -0.83452503,  0.02299665, -0.44233738,  1.77231896,
        2.45334958, -0.31647579, -0.69808224, -0.40342597,  0.19297488,
       -0.26545103,  1.51623904, -1.56999804,  1.63977014, -0.32886079,
        1.45268997,  0.27583138,  0.28760053,  0.71573539,  2.41024777,
        2.25727525, -0.06473421,  0.08481419, -1.92726289, -1.21671546,
        0.17594059, -0.92811179,  1.08250143, -0.15731949, -0.97630987,
       -0.20935279, -0.37126063, -0.76964357, -0.51873406,  0.72145577,
        0.60495749,  1.61099571,  0.41102954,  2.04749615, -0.24