In [1]:
"""
date : 2020/08/10
name : kang
content : Numpy 행렬실습하기
"""

'\ndate : 2020/08/10\nname : kang\ncontent : Numpy 행렬실습하기\n'

In [3]:
import numpy as np


In [5]:
#행렬 생성
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m3 = np.ones([2,4])
m4 = np.zeros([3,2])

In [7]:
m1

array([[1, 2],
       [3, 4]])

In [9]:
m2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
m3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
m4

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
#행렬 인덱싱
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])


In [18]:
matrix[0,0]

1

In [20]:
matrix[0,:]

array([1, 2, 3, 4])

In [22]:
matrix[1, :]

array([5, 6, 7, 8])

In [24]:
matrix[:, 0]

array([1, 5, 9])

In [27]:
matrix[:, 0:2]


array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [29]:
matrix[1:3, 1:4]

array([[ 6,  7,  8],
       [10, 11, 12]])